tenant: integration
app: integration
service: CHANGEME

provider:
  name: aws
  runtime: nodejs10.x

functions:
  # NodeJS handlers
  sync:
    handler: handler.sync
  syncError:
    handler: handler.syncError
  async:
    handler: handler.async
  asyncError:
    handler: handler.asyncError
  asyncDanglingCallback:
    handler: handler.asyncDanglingCallback
  callback:
    handler: handler.callback
  callbackError:
    handler: handler.callbackError
  noWaitForEmptyLoop:
    handler: handler.noWaitForEmptyLoop
  done:
    handler: handler.done
  doneError:
    handler: handler.doneError
  fail:
    handler: handler.fail
  succeed:
    handler: handler.succeed
  promise-and-callback-race:
    handler: handler.promiseAndCallbackRace
  spans:
    handler: handler.spans
  spans8:
    handler: handler.spans
    runtime: nodejs8.10

  # Python handlers
  pythonSuccess:
    handler: handler.success
    runtime: python3.7
  pythonSuccess2:
    handler: handler.success
    runtime: python2.7
  pythonError:
    handler: handler.error
    runtime: python3.7
  pythonHttpError:
    handler: handler.http_error
    runtime: python3.7
